name: ChirpStack API
on: [push, pull_request]
jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: Checkout googleapis repository
        uses: actions/checkout@v2
        with:
          repository: googleapis/googleapis
          path: googleapis
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: requirements
        run: |
          mkdir -p java/googleapis-proto
          cp -r googleapis/google/api/*.proto java/googleapis-proto/
      - name: build
        working-directory: java
        run: mvn --no-transfer-progress package
