name: ChirpStack API
on: [push, pull_request]
jobs:
  make-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}@${{ github.ref }}
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: build
        working-directory: java
        run: mvn package
